//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/Player/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""5e11b610-5582-4597-9f02-37a716a4c25d"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""98e97a2b-e9cb-4156-a473-f39374b067ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Button"",
                    ""id"": ""1d9e8842-2dcf-47c4-932e-70aab95edede"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""3981a2dd-a190-4f2d-a46b-163faa4bca7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstHook"",
                    ""type"": ""Button"",
                    ""id"": ""9b5d5df6-f841-4317-acdc-e8fa1c80d664"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondHook"",
                    ""type"": ""Button"",
                    ""id"": ""9fdb4fe0-4e14-4346-bd0f-e0007bcc24a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialGadget"",
                    ""type"": ""Button"",
                    ""id"": ""a74b8f3e-5924-4e41-a630-7d9c85ae8657"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""128afd5e-ef09-4c38-bcb3-ce65f0d72bfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeftWithBossFight"",
                    ""type"": ""Button"",
                    ""id"": ""2207516f-0940-407a-8fbf-1ab048c311f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRightWithBossFight"",
                    ""type"": ""Button"",
                    ""id"": ""435512f8-94b7-4436-8f2f-1096db4f716a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f5aadd87-c317-4403-b65a-148d8c24392a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07299f6e-b746-4113-ab0e-f8b845591f16"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1282c479-4d06-48ec-8aa4-a8c1753c9ec7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f286586-7308-46a1-9d3c-6ca31a88711c"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2217b4cb-a9b8-468f-a4a7-9f73517ecb7c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10243c5f-2da0-4d46-bb67-65cb2f2cdc64"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1f04b01-679a-40ea-8d22-767ab6ef5c4f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialGadget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af20509d-fad8-4a94-ae83-f4cc0a3fac7e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf61727b-e147-40b5-aac6-4b0b3cb46d20"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftWithBossFight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3916c41e-79ee-43fb-8c8a-a2c0a4f44448"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRightWithBossFight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Jump = m_PlayerInput.FindAction("Jump", throwIfNotFound: true);
        m_PlayerInput_Slide = m_PlayerInput.FindAction("Slide", throwIfNotFound: true);
        m_PlayerInput_Attack = m_PlayerInput.FindAction("Attack", throwIfNotFound: true);
        m_PlayerInput_FirstHook = m_PlayerInput.FindAction("FirstHook", throwIfNotFound: true);
        m_PlayerInput_SecondHook = m_PlayerInput.FindAction("SecondHook", throwIfNotFound: true);
        m_PlayerInput_SpecialGadget = m_PlayerInput.FindAction("SpecialGadget", throwIfNotFound: true);
        m_PlayerInput_Pause = m_PlayerInput.FindAction("Pause", throwIfNotFound: true);
        m_PlayerInput_MoveLeftWithBossFight = m_PlayerInput.FindAction("MoveLeftWithBossFight", throwIfNotFound: true);
        m_PlayerInput_MoveRightWithBossFight = m_PlayerInput.FindAction("MoveRightWithBossFight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Jump;
    private readonly InputAction m_PlayerInput_Slide;
    private readonly InputAction m_PlayerInput_Attack;
    private readonly InputAction m_PlayerInput_FirstHook;
    private readonly InputAction m_PlayerInput_SecondHook;
    private readonly InputAction m_PlayerInput_SpecialGadget;
    private readonly InputAction m_PlayerInput_Pause;
    private readonly InputAction m_PlayerInput_MoveLeftWithBossFight;
    private readonly InputAction m_PlayerInput_MoveRightWithBossFight;
    public struct PlayerInputActions
    {
        private @InputSystem m_Wrapper;
        public PlayerInputActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PlayerInput_Jump;
        public InputAction @Slide => m_Wrapper.m_PlayerInput_Slide;
        public InputAction @Attack => m_Wrapper.m_PlayerInput_Attack;
        public InputAction @FirstHook => m_Wrapper.m_PlayerInput_FirstHook;
        public InputAction @SecondHook => m_Wrapper.m_PlayerInput_SecondHook;
        public InputAction @SpecialGadget => m_Wrapper.m_PlayerInput_SpecialGadget;
        public InputAction @Pause => m_Wrapper.m_PlayerInput_Pause;
        public InputAction @MoveLeftWithBossFight => m_Wrapper.m_PlayerInput_MoveLeftWithBossFight;
        public InputAction @MoveRightWithBossFight => m_Wrapper.m_PlayerInput_MoveRightWithBossFight;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Slide.started += instance.OnSlide;
            @Slide.performed += instance.OnSlide;
            @Slide.canceled += instance.OnSlide;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @FirstHook.started += instance.OnFirstHook;
            @FirstHook.performed += instance.OnFirstHook;
            @FirstHook.canceled += instance.OnFirstHook;
            @SecondHook.started += instance.OnSecondHook;
            @SecondHook.performed += instance.OnSecondHook;
            @SecondHook.canceled += instance.OnSecondHook;
            @SpecialGadget.started += instance.OnSpecialGadget;
            @SpecialGadget.performed += instance.OnSpecialGadget;
            @SpecialGadget.canceled += instance.OnSpecialGadget;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @MoveLeftWithBossFight.started += instance.OnMoveLeftWithBossFight;
            @MoveLeftWithBossFight.performed += instance.OnMoveLeftWithBossFight;
            @MoveLeftWithBossFight.canceled += instance.OnMoveLeftWithBossFight;
            @MoveRightWithBossFight.started += instance.OnMoveRightWithBossFight;
            @MoveRightWithBossFight.performed += instance.OnMoveRightWithBossFight;
            @MoveRightWithBossFight.canceled += instance.OnMoveRightWithBossFight;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Slide.started -= instance.OnSlide;
            @Slide.performed -= instance.OnSlide;
            @Slide.canceled -= instance.OnSlide;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @FirstHook.started -= instance.OnFirstHook;
            @FirstHook.performed -= instance.OnFirstHook;
            @FirstHook.canceled -= instance.OnFirstHook;
            @SecondHook.started -= instance.OnSecondHook;
            @SecondHook.performed -= instance.OnSecondHook;
            @SecondHook.canceled -= instance.OnSecondHook;
            @SpecialGadget.started -= instance.OnSpecialGadget;
            @SpecialGadget.performed -= instance.OnSpecialGadget;
            @SpecialGadget.canceled -= instance.OnSpecialGadget;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @MoveLeftWithBossFight.started -= instance.OnMoveLeftWithBossFight;
            @MoveLeftWithBossFight.performed -= instance.OnMoveLeftWithBossFight;
            @MoveLeftWithBossFight.canceled -= instance.OnMoveLeftWithBossFight;
            @MoveRightWithBossFight.started -= instance.OnMoveRightWithBossFight;
            @MoveRightWithBossFight.performed -= instance.OnMoveRightWithBossFight;
            @MoveRightWithBossFight.canceled -= instance.OnMoveRightWithBossFight;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnFirstHook(InputAction.CallbackContext context);
        void OnSecondHook(InputAction.CallbackContext context);
        void OnSpecialGadget(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnMoveLeftWithBossFight(InputAction.CallbackContext context);
        void OnMoveRightWithBossFight(InputAction.CallbackContext context);
    }
}
